apiVersion: v1
kind: List
items:
- kind: Namespace
  apiVersion: v1
  metadata:
    name: stackdriver
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      name: prometheus
    name: prometheus
    namespace: stackdriver
  spec:
    selector:
      app: prometheus
    type: ClusterIP
    ports:
    - name: prometheus
      protocol: TCP
      port: 9090
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: prometheus
    namespace: stackdriver
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: prometheus
    template:
      metadata:
        name: prometheus
        namespace: stackdriver
        labels:
          app: prometheus
        annotations:
          prometheus.io/scrape: 'true'
      spec:
        # Needed when using unmodified rbac-setup.yml
        serviceAccountName: prometheus
        containers:
        - name: prometheus
          image: gcr.io/prometheus-to-sd/stackdriver-prometheus:master
          # Uncomment this to enable debug logs. Can be very verbose.
          #args: ["--config.file=/etc/prometheus/prometheus.yml", "--log.level=debug"]
          # Helps during development, when reusing the tag.
          imagePullPolicy: Always
          ports:
          - name: web
            containerPort: 9090
          volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
        volumes:
        - name: config-volume
          configMap:
            name: prometheus
- kind: ConfigMap
  apiVersion: v1
  data:
    prometheus.yml: |
      # Source: https://github.com/stackdriver/prometheus/blob/master/documentation/examples/prometheus.yml
      global:
        external_labels:
          _stackdriver_project_id: 'prometheus-to-sd'
          _kubernetes_cluster_name: 'prom-test-cluster-2'
          _kubernetes_location: 'us-central1-a'

      remote_write:
      - url: "https://monitoring.googleapis.com:443/"
        queue_config:
          # Capacity should be 2*max_samples_per_send.
          capacity: 400
          max_samples_per_send: 200
          max_shards: 10000
        write_relabel_configs:
        # These labels are generally redundant with the Stackdriver monitored resource labels.
        - source_labels: [job]
          target_label: job
          replacement: ""
        - source_labels: [instance]
          target_label: instance
          replacement: ""
  metadata:
    name: prometheus
    namespace: stackdriver
